import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart3,
  Building2,
  CalendarClock,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  Code,
  Code2,
  Cpu,
  DollarSign,
  Eye,
  Facebook,
  FileCheck,
  Gauge,
  Globe,
  Handshake,
  HeartHandshake,
  HeartPulse,
  Headphones,
  Instagram,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  Linkedin,
  ListChecks,
  Loader2,
  Mail,
  MapPin,
  Megaphone,
  Menu,
  MessageSquareQuote,
  Minus,
  Package,
  PackageCheck,
  Palette,
  PencilRuler,
  Percent,
  Phone,
  PlayCircle,
  Plus,
  Quote,
  Repeat,
  Rocket,
  Search,
  Send,
  Server,
  Settings2,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  Store,
  Tag,
  Target,
  Timer,
  TrendingUp,
  Truck,
  Twitter,
  Upload,
  Users,
  UserPlus,
  UsersRound,
  Utensils,
  X,
  Youtube,
  Zap,
  type LucideIcon,
} from "lucide-react";

import type { ComponentProps } from "react";

export const iconMap = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  "badge-check": BadgeCheck,
  "bar-chart": BarChart3,
  "building-2": Building2,
  "calendar-clock": CalendarClock,
  check: Check,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  "code-2": Code2,
  cpu: Cpu,
  "dollar-sign": DollarSign,
  eye: Eye,
  facebook: Facebook,
  "file-check": FileCheck,
  gauge: Gauge,
  globe: Globe,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  "heart-pulse": HeartPulse,
  headphones: Headphones,
  instagram: Instagram,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  lightbulb: Lightbulb,
  "line-chart": LineChart,
  linkedin: Linkedin,
  "list-checks": ListChecks,
  "loader-2": Loader2,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  menu: Menu,
  "message-square-quote": MessageSquareQuote,
  minus: Minus,
  package: Package,
  "package-check": PackageCheck,
  palette: Palette,
  "pencil-ruler": PencilRuler,
  percent: Percent,
  phone: Phone,
  "play-circle": PlayCircle,
  plus: Plus,
  quote: Quote,
  repeat: Repeat,
  rocket: Rocket,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings2,
  shield: Shield,
  "shield-check": ShieldCheck,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  store: Store,
  tag: Tag,
  target: Target,
  timer: Timer,
  "trending-up": TrendingUp,
  truck: Truck,
  twitter: Twitter,
  upload: Upload,
  users: Users,
  "user-plus": UserPlus,
  "users-round": UsersRound,
  utensils: Utensils,
  x: X,
  youtube: Youtube,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

type IconProps = ComponentProps<LucideIcon> & { name: string };

/** Render a Lucide icon by its string key. Falls back to a sparkle if unknown. */
export function Icon({ name, ...props }: IconProps) {
  const Cmp = iconMap[name as IconName] ?? Sparkles;
  return <Cmp {...props} />;
}
